_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 1203
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_VERSION: "FL"
      TEMPERATURE: 0.7
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [60000, 100000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
SEED: 37756442

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  GAMMA: 0.5
  STEPS: (80000,130000)
  MAX_ITER: 150000 # 150000 * 16 / 100000 ~ 10 epochs
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100

DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

TEST:
  AUG:
    ENABLED: True
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
  EVAL_PERIOD: 15000

OUTPUT_DIR: "checkpoints/lvis/faster_rcnn/all_FL_IoU_0.7"