_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "checkpoints/lvis/faster_rcnn/all_GC_IoU_0.7/model_0169999.pth" #"detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 1203
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      LOSS_VERSION: "GC"
      TEMPERATURE: 0.7
      LOSS_WEIGHT: 0.01
      DECAY:
        ENABLED: True
        STEPS: [80000, 120000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency
SEED: 37756442

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  # GAMMA: 0.5
  STEPS: (120000,160000)
  MAX_ITER: 180000 # 180000 * 16 / 100000 ~ 20 epochs
  # CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100

DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

TEST:
  # AUG:
  #   ENABLED: True
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
  # EVAL_PERIOD: 15000

OUTPUT_DIR: "checkpoints/lvis/faster_rcnn/all_GC_IoU_0.7"